on:
  workflow_dispatch: 
  pull_request:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible Inventory Check
        run:  bash test.sh
